%-----------------------------------------------------------------------
% Job saved on 02-Jul-2025 11:18:55 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
%%
matlabbatch{1}.spm.spatial.realignunwarp.data.scans = {
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,1'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,2'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,3'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,4'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,5'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,6'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,7'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,8'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,9'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,10'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,11'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,12'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,13'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,14'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,15'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,16'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,17'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,18'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,19'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,20'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,21'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,22'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,23'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,24'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,25'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,26'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,27'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,28'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,29'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,30'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,31'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,32'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,33'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,34'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,35'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,36'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,37'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,38'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,39'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,40'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,41'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,42'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,43'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,44'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,45'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,46'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,47'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,48'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,49'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,50'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,51'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,52'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,53'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,54'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,55'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,56'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,57'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,58'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,59'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,60'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,61'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,62'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,63'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,64'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,65'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,66'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,67'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,68'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,69'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,70'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,71'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,72'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,73'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,74'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,75'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,76'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,77'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,78'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,79'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,80'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,81'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,82'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,83'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,84'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,85'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,86'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,87'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,88'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,89'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,90'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,91'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,92'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,93'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,94'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,95'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,96'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,97'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,98'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,99'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,100'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,101'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,102'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,103'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,104'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,105'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,106'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,107'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,108'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,109'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,110'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,111'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,112'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,113'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,114'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,115'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,116'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,117'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,118'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,119'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,120'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,121'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,122'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,123'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,124'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,125'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,126'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,127'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,128'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,129'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,130'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,131'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,132'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,133'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,134'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,135'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,136'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,137'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,138'
                                                       'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-66\ses-T1\func\sub-66_ses-T1_task-SLD_bold.nii\sub-66_ses-T1_task-SLD_bold.nii,139'
                                                       };
%%
matlabbatch{1}.spm.spatial.realignunwarp.data.pmscan = '';
matlabbatch{1}.spm.spatial.realignunwarp.eoptions.quality = 0.9;
matlabbatch{1}.spm.spatial.realignunwarp.eoptions.sep = 4;
matlabbatch{1}.spm.spatial.realignunwarp.eoptions.fwhm = 5;
matlabbatch{1}.spm.spatial.realignunwarp.eoptions.rtm = 0;
matlabbatch{1}.spm.spatial.realignunwarp.eoptions.einterp = 2;
matlabbatch{1}.spm.spatial.realignunwarp.eoptions.ewrap = [0 0 0];
matlabbatch{1}.spm.spatial.realignunwarp.eoptions.weight = '';
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.basfcn = [12 12];
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.regorder = 1;
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.lambda = 100000;
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.jm = 0;
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.fot = [4 5];
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.sot = [];
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.uwfwhm = 4;
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.rem = 1;
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.noi = 5;
matlabbatch{1}.spm.spatial.realignunwarp.uweoptions.expround = 'Average';
matlabbatch{1}.spm.spatial.realignunwarp.uwroptions.uwwhich = [2 1];
matlabbatch{1}.spm.spatial.realignunwarp.uwroptions.rinterp = 7;
matlabbatch{1}.spm.spatial.realignunwarp.uwroptions.wrap = [0 0 0];
matlabbatch{1}.spm.spatial.realignunwarp.uwroptions.mask = 1;
matlabbatch{1}.spm.spatial.realignunwarp.uwroptions.prefix = 'u';
matlabbatch{2}.spm.temporal.st.scans{1}(1) = cfg_dep('Realign & Unwarp: Unwarped Images (Sess 1)', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','sess', '()',{1}, '.','uwrfiles'));
matlabbatch{2}.spm.temporal.st.nslices = 32;
matlabbatch{2}.spm.temporal.st.tr = 2;
matlabbatch{2}.spm.temporal.st.ta = 1.9375;
matlabbatch{2}.spm.temporal.st.so = [1.005 0 1.0675 0.0625 1.13 0.1275 1.1925 0.19 1.255 0.2525 1.3175 0.315 1.38 0.3775 1.4425 0.44 1.5075 0.5025 1.57 0.565 1.6325 0.6275 1.695 0.69 1.7575 0.7525 1.82 0.8175 1.8825 0.88 1.945 0.9425];
matlabbatch{2}.spm.temporal.st.refslice = 1000;
matlabbatch{2}.spm.temporal.st.prefix = 'a';
matlabbatch{3}.spm.spatial.coreg.estimate.ref = {'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-17\ses-T1\anat\sub-17_ses-T1_T1w.nii\skullStripped_biasCorrected_T1.nii,1'};
matlabbatch{3}.spm.spatial.coreg.estimate.source(1) = cfg_dep('Realign & Unwarp: Unwarped Mean Image', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','meanuwr'));
matlabbatch{3}.spm.spatial.coreg.estimate.other(1) = cfg_dep('Slice Timing: Slice Timing Corr. Images (Sess 1)', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('()',{1}, '.','files'));
matlabbatch{3}.spm.spatial.coreg.estimate.eoptions.cost_fun = 'nmi';
matlabbatch{3}.spm.spatial.coreg.estimate.eoptions.sep = [4 2];
matlabbatch{3}.spm.spatial.coreg.estimate.eoptions.tol = [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001];
matlabbatch{3}.spm.spatial.coreg.estimate.eoptions.fwhm = [7 7];
matlabbatch{4}.spm.spatial.normalise.write.subj.def = {'C:\Debashis\Research\AAAI_2025\fMRI_DDSA_Denmark_Dataset\fMRI_DDSA_Denmark_Dataset\Prediction_Analysis\Training\ADHD\Functional_Preprocessing\sub-17\ses-T1\anat\sub-17_ses-T1_T1w.nii\y_sub-17_ses-T1_T1w.nii'};
matlabbatch{4}.spm.spatial.normalise.write.subj.resample(1) = cfg_dep('Coregister: Estimate: Coregistered Images', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','cfiles'));
matlabbatch{4}.spm.spatial.normalise.write.woptions.bb = [-78 -112 -70
                                                          78 76 85];
matlabbatch{4}.spm.spatial.normalise.write.woptions.vox = [1.719 1.719 3.48];
matlabbatch{4}.spm.spatial.normalise.write.woptions.interp = 7;
matlabbatch{4}.spm.spatial.normalise.write.woptions.prefix = 'w';
matlabbatch{5}.spm.spatial.smooth.data(1) = cfg_dep('Normalise: Write: Normalised Images (Subj 1)', substruct('.','val', '{}',{4}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('()',{1}, '.','files'));
matlabbatch{5}.spm.spatial.smooth.fwhm = [3.438 3.438 6.96];
matlabbatch{5}.spm.spatial.smooth.dtype = 0;
matlabbatch{5}.spm.spatial.smooth.im = 0;
matlabbatch{5}.spm.spatial.smooth.prefix = 's';
